[package]
name = "hail"
version = "0.1.0"
edition = "2024"

[profile.profiling]
inherits = "release"
debug = true

# Slow?
#[profile.production]
#inherits = "release"
#lto = "fat"
##strip = true
#codegen-units = 1

[dependencies]
hashbrown = "0.16.1"
rhai = { version = "1.24.0", default-features = false, features = [
	"internals",
	"no_custom_syntax",
	"only_i64",
	"std",
	"unchecked",
]}
